### ISSUE TITLE
View all transactions on wallet in block explorer shows only latest transaction

### ISSUE THREAD

**Issue by andreasenglund** [ellaism/meta#11]
Checking view All transactions on a wallet in the block explorer only shows the latest transaction.

**Comment by andreasenglund** [comment]
![screenshot_20171227-130240](https://user-images.githubusercontent.com/713017/34381163-0a62f9f4-eb07-11e7-8772-6325a734ecd6.png)

**Comment by riddlez666** [comment]
Closing topic due to new explorer release which solved outstanding issues.
