### ISSUE TITLE
Explorer Wishlist

### ISSUE THREAD

**Issue by ellaismer** [ellaism/meta#12]
Here're new features requested to add to the explorer. Please feel free to reply with the thing you want to see.

#### @ellaismer's List

Below are features that @ellaismer also highly thinks should be done first, but haven't got a planned date for implementation.

- [x] Open source the explorer.

#### New

- [ ] Show confirmation counts for transactions.
- [x] Favicon and ether to ella typos for coin consistency.
- [ ] Intergrate stats.ellaism.org to show blocktime hash and difficulty.
- [x] Add a link or integrate richlist.
- [ ] Merge mikes explorer edits into ours.

**Comment by riddlez666** [comment]
Favicon and ether to ella typos for coin consistency.

**Comment by tbates76** [comment]
Perhaps we can intergrate stats.ellaism.org to show blocktime hash and difficulty. Also a link to richlist

**Comment by mike-theminer** [comment]
Hi, I'm a freelance dev from nekonium (eth clone). I developed http://nekonium.network/ . Would you like to have this kind of explorer on ellaism ? I can customize + add functionalities to the explorer as your requirements

**Comment by ellaismer** [comment]
@mike-theminer Yeah definitely. If it works well, we can replace the current buggy explorer.ellaism.org. :)

**Comment by riddlez666** [comment]
@ellaismer Does this explorer show confirmation count? i'm updating this issue.

**Comment by riddlez666** [comment]
Rich list is/was integrated.
