### ISSUE TITLE
Project: Myellawallet

### ISSUE THREAD

**Issue by riddlez666** [ellaism/meta#14]
- [x] favicon and all myetherwallet references replaced with myellawallet, example is printing paper wallets.

- [x] finish dns for myellawallet.com once domain is transfered EST Jan 3-4.

[myellawallet](https://github.com/ellaism/ellawallet)

**Comment by cryptowd** [comment]
Hi, I can help a bit with updating text and artwork for Myellawallet.  Most of the Ethereum references seem fixed, but I can help with any other basic cosmetic updates-- like the paper wallet label.

I believe I need write permission to branch it and and then do a pull request.  I'm new to this github thing.

Sample attached.

![print-sidebar](https://user-images.githubusercontent.com/34805878/35804239-8e0ac9cc-0a3c-11e8-977d-76090b28c27f.png)

**Comment by ellaismer** [comment]
@cryptowd Thank you! Please do!

I invited you as a member to this Github org. You can push changes first to a fork in your own Github username, and then using that to send PRs.
