### ISSUE TITLE
Discussion Community Wallet uses

### ISSUE THREAD

**Issue by tbates76** [ellaism/meta#16]
TBates76 - Today at 3:37 PM
opening up discussion on payment to devs and use of community funds
@ everyone Idea has been suggested to make fund especially for exchange listings.  
So there is no confusion the community fund is set to pay for community devs and in the future server costs if need be. Or as the community votes as needed
(edited)
ɃuzzkillɃ 🔺 - Today at 4:29 PM
@everyone
Jurassikbart - Today at 4:29 PM
?
shisa-shiba - Today at 4:29 PM
I have been summoned
CoachCryptos - Today at 4:29 PM
?!?
strangerlefty - Today at 4:30 PM
I think we need to figure how to get on more exchanges.
ɃuzzkillɃ 🔺 - Today at 4:30 PM
look at what tbates posted
CHRlS - MINERPOOL.NET - Today at 4:30 PM
the community fund is for all things the community managers want to do with it
but thought mostly for marketing, campaigns and things
and not usual for paying devs
Riddlez666 ツ ☠ - Today at 4:32 PM
so what pays the devs then @CHRlS - MINERPOOL.NET since you are chiming in now
CHRlS - MINERPOOL.NET - Today at 4:32 PM
no idea, the dev fund?
ɃuzzkillɃ 🔺 - Today at 4:34 PM
this is for everyone to discuss so everyone please chime in with the purples :smiley:
Riddlez666 ツ ☠ - Today at 4:34 PM
good to know you have been listening the whole time :ok_hand:
giggle1
core and community are different
CHRlS - MINERPOOL.NET - Today at 4:34 PM
@Count Cryptula  wanted an idea from me to pay things the community managers do(edited)
and this was why I found the idea of the community fund which is funded by pools(edited)
@Count Cryptula
Riddlez666 ツ ☠ - Today at 4:35 PM
yea then i get bullshit like why are you running a pool if you get payed...
i now have 0% fee cause of it
CHRlS - MINERPOOL.NET - Today at 4:36 PM
i have no idea tbh derek ... this only was what count and me did initially
Mobius-1 - Today at 4:37 PM
@Riddlez666 ツ ☠ wait you removed your pool fee?
looks at mining well damn I guess you did
</endofftopic>
Count Cryptula - Today at 4:39 PM
the original community fund goals were for marketing, bounties and future payment for exchanges. Also for occasional payments to devs - particularly community devs, but we have paid some to the core as well
the fund was not meant to be for predominantly for paying devs, but we have occasionally done so. The community devs have no access to the dev fund unless @ellaismer  wants to pay them out of that
CHRlS - MINERPOOL.NET - Today at 4:41 PM
i know there was a payment to community devs i don't wanted to have for me and i didn't took it
TBates76 - Today at 4:42 PM
This is just an open discussion for what to do next
CHRlS - MINERPOOL.NET - Today at 4:42 PM
but that was my personal choice
ellaismer - Today at 4:43 PM
Indeed I cannot abruptly use dev fund. It is meant to fuel core development, but right now, similar to community fund, there're many things undecided and there's only one expense (200 ELLA) paid to a designer for Ellaism website design (shared with Community Fund @Count Cryptula and @Riddlez666 ツ ☠) as of now. And I do also want to note to everyone that for me personally, I won't get paid by any means unless I decided to work on Ellaism full time.(edited)
Another thing I want to note is that all community signers do collectively have one signature in the Dev Fund. So if Community Fund signers and @sorpaas agree on some ways to use Dev Fund, there would be nothing I can do to stop it.
CHRlS - MINERPOOL.NET - Today at 4:45 PM
so, it is like it was all the time if i understand it correctly
dev fund = mainly core dev things (e.g. servers and so on, later perhaps paid devs)(edited)
community fund = mainly marketing things (bounties, exchange fees and so on)
TBates76 - Today at 4:46 PM
so community devs such as yourself get paid from where?
Riddlez666 ツ ☠ - Today at 4:47 PM
or me who is always here...
CHRlS - MINERPOOL.NET - Today at 4:47 PM
from nowhere
no ongoing income out of a fund at the moment
that's the difference between a core dev and a community dev then
Riddlez666 ツ ☠ - Today at 4:48 PM
and this is why a had a pool fee...
to a pool thats slowly dieing non the less
CHRlS - MINERPOOL.NET - Today at 4:48 PM
apart of the fact that ellaismer doesn't pays himself as for now
if the community managers decide that enough coins are together to pay something to a highly active dev (like riddlez) then this is something like "the exception of the rule" we would say in germany(edited)
TBates76 - Today at 4:51 PM
we say that here in USA too
ɃuzzkillɃ 🔺 - Today at 4:51 PM
yeah thats what I think we are trying to figure out
CHRlS - MINERPOOL.NET - Today at 4:52 PM
but, if i understand this correctly too, the community fund is completely free for the CM team to be given into any direction they decide freely
this was at least the initial thought, a fund that is decided by the cm, not the core
TBates76 - Today at 4:53 PM
That has been achieved
ɃuzzkillɃ 🔺 - Today at 4:53 PM
I also think there is enough to pay out to community devs right now
TBates76 - Today at 4:54 PM
now we need to set a goal for it and I think we can take some out to for the active devs
CHRlS - MINERPOOL.NET - Today at 4:54 PM
you must have the vision how many is enough ^^
Riddlez666 ツ ☠ - Today at 4:55 PM
Im not core nor am i key signer im a dude thats giving my all to something.
CHRlS - MINERPOOL.NET - Today at 4:56 PM
the problem is this is a fund which was created for things like bounties, exchanges, and so on cause no hardfork was wished to implement an ongoing fund
which means, every coin which is given out could be missing for some other action
ɃuzzkillɃ 🔺 - Today at 4:56 PM
what actions are important to the community outside of paying the community devs?
CHRlS - MINERPOOL.NET - Today at 4:57 PM
and in some time, if the voices get louder for bigger exchanges, i only can say these are really expensive
ɃuzzkillɃ 🔺 - Today at 4:57 PM
any ideas on some BTC numbers for the larger exchanges?
CHRlS - MINERPOOL.NET - Today at 4:57 PM
this community dev thing came later tbh
and normally it should give campaigns and these marketing things out of these funds
larger exchanges between 20 - 30 btc
ɃuzzkillɃ 🔺 - Today at 4:58 PM
ugh
TBates76 - Today at 4:59 PM
larger as in polonex/bittrex?
CHRlS - MINERPOOL.NET - Today at 4:59 PM
larger as in hitbtc, binance
ɃuzzkillɃ 🔺 - Today at 4:59 PM
you are pretty sure about 20-30 for binance?
CHRlS - MINERPOOL.NET - Today at 5:00 PM
about binance i only know that they are choosing the coins themself apart of the payment
and that they are really expensive
about hitbtc i know that they are between 20 - 30 btc meanwhile
but someone mentioned that even cryptopia asks 20 btc meanwhile
TBates76 - Today at 5:06 PM
So I suggest we do this...
ellaismer - Today at 5:06 PM
@DEVS I don't have a saying in whether community fund pays devs (I think this is a thing that should be decided by #umbrella), but I do see an opportunity here that would allow us to set up a third donation fund. In my opinion, having more donation funds mean we can better decentralize the development process. But you guys will need to figure out details about the multisig -- How many signers do you want? Who are allowed to be on the signature?
We can call it "Contributor Fund" which just pays any developers or contributors to Ellaism, or "Community Development Fund" (but this name looks quite similar to Community Fund and Dev Fund, so not recommended). I'll list this in https://ellaism.org/donate if we agree and are able to set it up.
Ellaism
Donate to Ellaism
An Ethereum-like network with no premine and no contentious hard forks.

👍3
TBates76 - Today at 5:07 PM
I think for now to keep it at the 2 funds
in the future we can go to that model as it Ellaism becomes more popular.
What I suggest is to lets take a vote on a payout for "past and continued" development then set anything left towards a goal
ultramenid - Today at 5:10 PM
ppl  want more exchange atm :tired_face:
Riddlez666 ツ ☠ - Today at 5:11 PM
the  exchanges need to get there shit together
Gos - Today at 5:12 PM
And what about kucoin? Hard to list there?
TBates76 - Today at 5:12 PM
werent they just compromised?
CHRlS - MINERPOOL.NET - Today at 5:12 PM
not hard to be listed, but costs money too
terra-pescado - Today at 5:13 PM
Need binance listing
osoese - Today at 5:13 PM
I know its a 2nd rate exchange but has anyone considered COSS.io ? you may be able to work a triforce situation out with coss who knows...list all of the coins. Their site says they are open to negotiate on the fee.
CHRlS - MINERPOOL.NET - Today at 5:14 PM
i would prefer @ellaismer idea with the third fund
TBates76 - Today at 5:14 PM
@Gos sorry it was coincheck
osoese - Today at 5:14 PM
binance seems to be a community vote reality - where if you have a massive social media following it is easier to get listed
CHRlS - MINERPOOL.NET - Today at 5:15 PM
in my opinion should the community fund remain what it was thought for
Aurocheen - Today at 5:15 PM
Quite like the 3rd fund idea as well
ɃuzzkillɃ 🔺 - Today at 5:16 PM
@osoese I am trying to watch this closely to see if we can work this in with triforce coins
ellahaze2
triforce31
CHRlS - MINERPOOL.NET - Today at 5:16 PM
it is of course only my personal opinion that bounty campaigns, exchanges and these things are at least not unimportant, but that was the initial idea of this fund(edited)
@Count Cryptula what do you think?
Gos - Today at 5:19 PM
Ella is too young for binance/bittrex i think. If we want to real and natural growth and not depend on some pump and dump effect
ELLABOT - Today at 5:19 PM
Ok I will add that fact about ella to my database.      That is deep.
pepe2
Gos - Today at 5:19 PM
woops
CHRlS - MINERPOOL.NET - Today at 5:19 PM
:joy:
Gos - Today at 5:20 PM
really deep haha
Mobius-1 - Today at 5:20 PM
:thinking:
0xcaffe - Today at 5:20 PM
hidden feature of the ella bot?
CHRlS - MINERPOOL.NET - Today at 5:21 PM
learning module of her ki module ^^
0xcaffe - Today at 5:21 PM
is the source code of the bot on github? :nerd:
CHRlS - MINERPOOL.NET - Today at 5:21 PM
of the ki it is
0xcaffe - Today at 5:22 PM
the bot doesn't respond to the joke command anymore :disappointed_relieved:
ɃuzzkillɃ 🔺 - Today at 5:23 PM
I think it could be time to pay the active community devs
because working for free kind of sucks
but is everyone just looking for new exchanges? or anything else that could help ellaism out like hardware wallet support, bounties, marketing, etc.?
CHRlS - MINERPOOL.NET - Today at 5:24 PM
but not regularly out of the funds for other things is the only thing i mean
Count Cryptula - Today at 5:25 PM
I agree that the main purpose of the community fund should be marketing and exchanges. In my opinion, it is most important right now to conserve and grow those funds for possible exchanges. That being said, I think we can carve out a reasonable reward for those doing ongoing work like Riddlez on occasion - until another fund is created
CHRlS - MINERPOOL.NET - Today at 5:27 PM
I had prefered a hardfork to implement a ongoing dev fund to pay the devs ongoing and all the other things btw
devs must be paid, they cannot work ongoing for nothing
ɃuzzkillɃ 🔺 - Today at 5:27 PM
I kind of like this as it gets you guys discussing what to do
Mobius-1 - Today at 5:30 PM
I tend to agree w/ @Count Cryptula. Is it already agreed on (or is there significant support for) a future 3rd fund?
Riddlez666 ツ ☠ - Today at 5:30 PM
The confusion is from having the funds and then people asking me dont you get payed from it, so why have a pool fee.
My pool was a way for me to support myself and the community since i was doanting 50% of the 1%.
which has now turned into a expense compared to a leg up
now its not all my fault this is on the table but this should be sorted out as im pretty sure alot of you value what ive done a broughten here.
ellamoon4
Gos - Today at 5:34 PM
maybe somehow include pay content? People who want to support can buy something and those funds transfer on community wallet
ellaismer - Today at 5:34 PM
Just for anyone not in this coin from the beginning, I'm always against @CHRlS - MINERPOOL.NET's idea of having dev fees. I created this coin because I want something pure and free of dev fees or premine (although after the creation everyone's free to interpret it whatever way they like). I think it is important to keep this property. There're many ways we can pay devs. Donations being one of them (Monero as an example). There're also many other ways like third-party fundings, recurring payments, etc. After all, open source developers have been keeping things pure and free for decades. And as a pure coin, we shouldn't sacrifice purity if there's other ways to accomplish the goal.
ella12
Mobius-1 - Today at 5:38 PM
the chat room falls silent as the master has spoken
ɃuzzkillɃ 🔺 - Today at 5:39 PM
that happens from time to time
Aurocheen - Today at 5:42 PM
Just throwing an idea out about a future 3rd fund, could still be run by donations, but how about it being like a payroll plan dividing the funds between certain key contributors every month, and then with the 2 other funds those groups can also still ahve the option to reward on occasitions
then community/investors have a more direct way of putting in funds to go to paying your guys behind the curtains
Not thinking it would be equally divided, thinking at first someone from core and someone from communty dev team could setup names and a possible spread and could be reviewed from time to time as things change
Riddlez666 ツ ☠ - Today at 5:49 PM
i could set my pool up as the 3rd pool for the purpose also
but who knows
ɃuzzkillɃ 🔺 - Today at 5:50 PM
would a 3rd fund start with any ella from the other funds?
or start from 0?
TBates76 - Today at 5:51 PM
could be voted for that to happen
ɃuzzkillɃ 🔺 - Today at 5:51 PM
can we use the voting dapp for this?
Riddlez666 ツ ☠ - Today at 5:51 PM
that app is a nightmare and needs to be redone @ɃuzzkillɃ 🔺
ɃuzzkillɃ 🔺 - Today at 5:52 PM
how do we vote for lets say a 3rd fund?
Aurocheen - Today at 5:52 PM
I could see it start from 0, I will donate the first 100 even if its not much
TBates76 - Today at 5:52 PM
does it work now?
ɃuzzkillɃ 🔺 - Today at 5:52 PM
i will donate as well as long as we have some direction
Riddlez666 ツ ☠ - Today at 5:53 PM
it works for yes or no and hasnt been touched ina bit needs to get assigned to be redone
ima talk with OZ on the voting but for now its non functional basically
i was redoing the front end and have been caught up with ellagem and well ya know how that goes(edited)
TBates76 - Today at 5:56 PM
Ellagem "once you look into it you cannot look away"
Riddlez666 ツ ☠ - Today at 5:57 PM
god if you only knew lol @osoese knows the ellagem rabbit hole(edited)
sorpaas - Today at 5:59 PM
Rick Falkvinge: Don’t ask permission in a permissionless system.
sorpaas - Today at 6:00 PM
Up for a fund? Just create it!
Riddlez666 ツ ☠ - Today at 6:00 PM
Easier to ask for forgivness than permission
sorpaas - Today at 6:00 PM
By the way, nice discussion here, everyone!
TBates76 - Today at 6:01 PM
very cordial
osoese - Today at 6:02 PM
well, ellegem can be a bit overwhelming and i started over with a lite wallet after contacting frozeman (mist dev) a few times for small update information
the price conversion was hardcoded to eth in a meteor package....so instead of rewiring all of that I just started a local copy because the code was easy to fix its all the dependencies and libraries that I don't know
TBates76 - Today at 6:04 PM
@osoese is now 3 steps down the rabbit hole
ellahaze1
ɃuzzkillɃ 🔺 - Today at 6:05 PM
so how do we pay our community devs??

osoese - Today at 6:06 PM
well, if we are going to distance ourselves from being an eth clone might as well start now....:yum:
Riddlez666 ツ ☠ - Today at 6:06 PM
yup
TBates76 - Today at 6:06 PM
Also this will allow the hiring of devs for project work
pay X for Y
ɃuzzkillɃ 🔺 - Today at 6:09 PM
how about taking some of the current community fund to pay the purples? anyone chime in on that?
TBates76 - Today at 6:09 PM
well heres my thinking
if the vote goes for new fund...
then the next action would be to allow payment to new fund from community fund
this way the community fund has no direct payment to any dev
Aurocheen - Today at 6:11 PM
well I dont think we are close to a new exchange with the funds right now, so I say rather pay some to devs and community devs to keep up the steam on the great work they are doing
and second the above as well
TBates76 - Today at 6:11 PM
I agree@Aurocheen  but this is more of laying the foundation for future things
Riddlez666 ツ ☠ - Today at 6:12 PM
we have exchanges applied for cryptobridge for example which i was given word we are in line for
ɃuzzkillɃ 🔺 - Today at 6:12 PM
I am strong on paying riddlez, chris and oso sooner than later
👍1
Riddlez666 ツ ☠ - Today at 6:12 PM
once they start adding eth coins we are in
ɃuzzkillɃ 🔺 - Today at 6:13 PM
they brought a lot to this before going to topia
Aurocheen - Today at 6:13 PM
Yeah and that would be great I think, once Cryptopia is back to a bit more normal operation again Im not worried
terra-pescado - Today at 6:22 PM
I agree, I believe in this coin and have been mining since I built my rig. Is there a cold storage device that is compatible with Ella?
Aurocheen - Today at 6:23 PM
trezor works with it
terra-pescado - Today at 6:23 PM
Oh nice, thanks
ellaismer - Today at 6:30 PM
@TBates76 @ɃuzzkillɃ 🔺 Though, let's use a proper CarbonVote next time. Traditional online voting system can be vulnerable to sybli attack, and that's why we need to vote on the blockchain. On another note, I do agree with @sorpaas that if someone's up for it, we can just go ahead and create it. This 3rd donation fund does not affect any existing things and there's indeed no need to ask permissions.
ɃuzzkillɃ 🔺 - Today at 6:31 PM
thats the thing, we need direction, and tbates just did it, but you are looking for a specific way of doing things
i hope that made sense
ellaismer - Today at 6:31 PM
Okay okay.
But just some suggestions. And personally I think next time, if we want to vote, sticking to vote on the blockchain using CarbonVote or MinerVote is important. We're a blockchain anyway. :laughing:
Riddlez666 ツ ☠ - Today at 6:33 PM
for a simple vote like that its not needed
ɃuzzkillɃ 🔺 - Today at 6:33 PM
i wanted to use the voting dapp, but its not ready it sounds like :smiley:
ellaismer - Today at 6:34 PM
@ɃuzzkillɃ 🔺 Though once community gets big, sybli attack will become common. At that time, even a really simple one would need to go through a blockchain. Otherwise any attacker can control the direction of the voting.
Next time give us devs at least 24 hours before calling it not ready please. :laughing:(edited)
ɃuzzkillɃ 🔺 - Today at 6:35 PM
easy enough
TBates76 - Today at 6:38 PM
That was a general direction vote
Riddlez666 ツ ☠ - Today at 6:38 PM
you cant use the blockchain for quick on the fly votes so im ok with how this one was done but well get the voting app ready and revamped
CHRlS - MINERPOOL.NET - Today at 6:39 PM
wow, already 22 votes
Mobius-1 - Today at 7:00 PM
added mine :smiley:
(i'm considering it an informal vote)
TBates76 - Today at 7:01 PM
That voting system is not secure so we not using that as a final(edited)
👍2
ellahaze1
MakeMoneyOz - ellaismpool.com - Today at 8:38 PM
I think we need to focus on how we will improve and take Ellaism further. While i 100% agree , people need to be paid. I dont believe personally we need another fund right now. We need to setup a guidance system for payments from out existing funds, when/if they payments dont meet those funds criteria, we can hold a vote to implement a new fund. The work being completed by  @Riddlez666 ツ ☠ @osoese 100% warrents some type of payment. While myself , im more inclinded to be with  @ellaismer and not take a payment unless i matching  @Riddlez666 ツ ☠ on time / development input.
@Riddlez666 ツ ☠ in terms on pool fees, i dont believe you should be asked/forced to lower your fees if your a dev. You are putting in the same time , effort and skill as other pool operators and it should be looked at accordingly(edited)
MakeMoneyOz - ellaismpool.com - Today at 8:42 PM
@ellaismer  i think this conversation should be archived for future reference/discussions

**Comment by Mininghomer** [comment]
I am not a dev but I am an enthusiast miner and I like everything about Ella. Right now i have 1 rig on Ella miner pool and 1 rig on Ella Dev pool would it be possible to have a pool with 1% fee 45%-Dev 45%Community and 10% Dev pay if this pool Option were available I would be an immediate contributor. I believe each fund is important to the growth of Ella.

**Comment by ellaismer** [comment]
Closing. The new Community Fund setup is in process.
