### ISSUE TITLE
Alter pool software to allow pool fee to be changed by user.

### ISSUE THREAD

**Issue by riddlez666** [ellaism/meta#18]
Find a way to make it so a user can select/modify the amount they want to donate from there block reward shares.

Using ella contracts and a discord bot.

- [ ] go/redis backend (might not be needed for pool.)
- [ ] Front end design and code
- [x] Thorough testing 
- [x] List of donation values confirmed and agreed to. (Custom due to bot)
- [ ] See value of estimated rewards to user and dev.
- [ ] Flags to specify where donation is mined to eg. --dev --com --con
- [ ] Source files published to GitHub, OPEN SOURCE!
- [ ] Basic documentation for user usage and explanation.

**Comment by riddlez666** [comment]
![screenshot_10](https://user-images.githubusercontent.com/32908855/36036888-ef0b86cc-0d6f-11e8-825c-f9f2ec007dd2.png)

**Comment by riddlez666** [comment]
@ellaismer been chatting with users and they would really like the option to do these things and i hope you will help :)

**Comment by ellaismer** [comment]
@riddlez666 Thanks for putting this up! I'm thinking about some simpler methods to do this before we jump in modifying the pool, because the later would need to completely change the unlocker which is a lot of work.

How about this: we use a customized splitter contract. When deploying, you specify a) wallet destination, and b) donation percentage. Like the Dev/Community Fund splitter, any fund sends to this address would be automatically distributed accordingly to the wallets without needing the user taking any extra steps.

Then the next thing is simply to create good interface for them. We can have a discord bot: `!splitter <address> <percent>` would return a splitter address. Then we simply instruct the user to put the splitter address when mining. We can also have web interfaces and in the end, directly embed this into the pool with an interface like you've described above.

How do you like this way?

**Comment by riddlez666** [comment]
If you feel its to much work and the contracts are easier please share the resource links so i can get upto speed on the bots. @ellaismer sharing the bot code/contracts might be a good idea also.

**Comment by ellaismer** [comment]
Will do. I'll try to get the bots up by next week. And open source everything once I cleaned the credentials.

**Comment by riddlez666** [comment]
Say somebody doesn't want to support all the addresses can we add a flag like -dev/-com/-con to specify where they want there donations sent this was one of the main ideas/concerns of the pool edits also.

**Comment by ellaismer** [comment]
@riddlez666 Yes!

**Comment by riddlez666** [comment]
I edited the check list a bit as a reference for everyone keeping track of this.

**Comment by riddlez666** [comment]
Adding comment/ request for pool software. [4:56 PM] huggermugger: @Riddlez666 ツ ☠ - pool.ellaism.io i'm mining on pool.ellaism.io do you think it would be possible to include a last 24 hour reward counter at some stage?

**Comment by ellaismer** [comment]
This is currently possible by using the SplitBot in Discord. The command format is

```
!split <dev|community|default> <percentage> <address>
```

It donates an additional `<percentage>` to Dev Fund, Community Fund, or the split address for Dev Fund and Community Fund, and then sends the rest of the funds to `<address>`.

For example,

```
!split dev 5% 0x65767ec6d4d3d18a200842352485cdc37cbf3a21
```

This would donate an additional 5% to Dev Fund, and sends the rest of the balance to `0x65767ec6d4d3d18a200842352485cdc37cbf3a21`. You can issue this command in `#ask-ella-bot` Discord channel, then the bot will give you an contract address. All you need to do then is to mine on this contract address.

**Comment by riddlez666** [comment]
@ellaismer this wasn't suppose to be out yet :(  Also this was the reason i was modding my pool...The contributor fund is missing can this be modified once its ready?

**Comment by ellaismer** [comment]
@riddlez666 Yes of course!

**Comment by cryptowd** [comment]
So I've tested this Splitbot on the Dev pool with a 5% dev fee and created a fresh wallet to mine to for testing.  I've set my miner to the address Splitbot sent me and it seems to be working fine for Ellaism coins which are being forwarded to my new wallet, however I do not seem to be receiving mining tokens.

**Comment by ellaismer** [comment]
@cryptowd The Split contract does not support receiving mining tokens yet. I'll get a fix soon!

**Comment by ellaismer** [comment]
@cryptowd MINING token support is added in SplitBot. Please re-deploy your Split contract. After that, at any time, you can issue:

```
!mining withdraw <split contract address>
```

And all your MINING tokens will be automatically sent to your wallet.

**Comment by cryptowd** [comment]
You are too fast!  Very cool.

**Comment by riddlez666** [comment]
No longer needed as a open issue.
