### ISSUE TITLE
Explorer Gas Price

### ISSUE THREAD

**Issue by riddlez666** [ellaism/meta#22]
@ellaismer I feel there might be a odd issue.
Should there be some gas used in this link?

https://explorer.ellaism.org/tx/0x7dc01e4d34244675b8eba631982460611f6dfefb450ade5205bcd107ea58d979

**Comment by ellaismer** [comment]
Fixed in https://github.com/ellaism/explorer/commit/64c16ee4e518b87d073956a3800c06321995bed3
