### ISSUE TITLE
Multi GETH

### ISSUE THREAD

**Issue by riddlez666** [ellaism/meta#25]
Ellaismer's Notes

1. We keep https://github.com/ellaism/go-ellaism using ETC's fork, and continue to merge ETC upstream patches. This way, we don't break anything for existing go-ellaism users.

2. We use https://github.com/ellaism/go-ethereum, which was started by @MakeMoneyOz - ellaismpool.com, as the base for multi geth version based on ETH.

3. We make the changes minimal -- we don't change golang import paths (keep it github.com/ethereum/go-ethereum). This makes it easier to merge upstream ETH changes.

4. I created a team called "multi-geth" for ellaism/go-ethereum, if you want to help developing multi-geth, please just ask me to add you to the team.

5. All changes for multi-geth go through pull requests. Master is set as protected branch.

**Comment by p-s-dev** [comment]
https://github.com/ellaism/go-ellaism  is old.

Project moved to https://github.com/ellaism/multi-geth

**Comment by ellaismer** [comment]
This project is taken over by Ethoxy, please find the new repo here: https://github.com/ethoxy/multi-geth
To prepare for the August hard fork enabling Byzantium and WebAssembly, existing users please upgrade to Parity v1.10.6+.
