### ISSUE TITLE
Discord Channel Reorg

### ISSUE THREAD

**Issue by stevemulligan** [ellaism/meta#41]
# Why?
There were a few people who mentioned they felt there were too many channels.  Drafting a proposed structure that seeks to eliminate unused channels and to make the experience for first time visitors a bit easier.  When I say "removed" it doesn't have to be deleted.  There can be an "ARCHIVE" category where all the removed channels go for instance.

# Proposed Structure

**INFORMATION**
 \# welcome
 \# announcements
 \# github-updates

_no changes_

**ELLAISM CHAT**
 \# general
 \# support
 \# telegram
 \# trading
 \# mining
 \# voting

_1. Moved #general-support up here, renamed to #support, this is to make it easier for new visitors to ask for help
2. Moved "bots, socials" channels elsewhere as they are for users that have been here longer than new people.  
3. "debate, tokens, ideas" removed as they seem to be covered by other channels, any they don't get much activity at this time
4. Renamed votings to voting.  Using singular, to be consistent with trading, mining (verbs) instead of using plural noun_

**BOTS**
 \# bots
 \# socials
_I'm not sure where to place this section.  Part of me feel that #bots should be part of the ELLAISM CHAT category. But then #socials is sitting alone out of place.  Maybe #socials could move to OPTIONAL but it still seems a bit out of place there still...._

 **UMBRELLA**
  \# development
  \# marketing
  \> meeting

_Removed "#umbrella" since we don't use it often and doesn't seem like we need a generic umbrella channel_

**WORKING GROUPS**
  \# code-of-conduct
  \# summer-of-code
  \# website-development
  \# exchange-listings
  \# social-networks
  \# ella-bots
  \# ella-dapps
  \# swag-store
  \# mobile-wallets
_1. Removed #wasm-hardfork, it should be done by the time this is sorted out
2. Removed #ella-games since we have #ella-dapps
3. Added #mobile-wallets working group_

_Removed Support category entirely since there is a support channel at the top of the list, and arguably, people who really need help will most likely post in #general the first time they visit._

**INTERNATIONAL**
_No changes, can we get a Canada channel?  jk!_

**OPTIONAL**
  \# welcome-area 
  \# memes
  \# off-topic
  
_Removed #watercooler as it seems to be covered by #off-topic_

**ARCHIVE**
_Deleted channels go here_

**Comment by ellaismer** [comment]
@stevemulligan I suggest we still keep the #wasm-hardfork working group right now. The hard fork isn't done yet and we still have some stuff to do!

**Comment by stevemulligan** [comment]
This is working out well.  I really like #support up near the top.  Closing.
