### ISSUE TITLE
Metamask integration

### ISSUE THREAD

**Issue by akx20000a** [ellaism/meta#45]
Currently I am working for metamask integration to add multiple ethereum-like network support for example Ethereum Classic or Expanse, Ethereum Social, etc.

I would like to suggest adding ellaism RPC port and it's following configs on my version of metamask also.

And I would like to hear any suggestions about supporting ellaism on Metamask 😄

**Comment by hackmod** [comment]
what the .... :(

Please see https://github.com/MetaMask/metamask-extension/pull/4516

**Comment by akx20000a** [comment]
@hackmod No I will not use your version of metamask ( It causes crash sometimes ) 

I am working on to improve ClassicMask with Callisto team and the updated binary will be published soon

**Comment by akx20000a** [comment]
@hackmod 야 좀 그만 따라다녀 노망났냐;;
