### ISSUE TITLE
Metamask integration

### ISSUE THREAD

**Issue by akx20000a** [ellaism/meta#46]
Currently I am working for metamask integration to add multiple ethereum-like network support for example Ethereum Classic or Expanse, Ethereum Social, etc.

I would like to suggest adding ellaism RPC port and it's following configs on my version of metamask also.

And I would like to hear any suggestions about supporting ellaism on Metamask 😄

@hackmod 깝치지 마라 씨발년아 꼬우면 기여하던가 병신이

**Comment by hackmod** [comment]
he continuously try to leak out my real life personal information (TEL, address) on github, discord channels, and swearing in Korean...

**Comment by akx20000a** [comment]
@hackmod Are you afraid for someone knocking your door??

**Comment by stevemulligan** [comment]
Guys come on, the point of open source is to share code and work together, no need to act like this is Amazon vs Microsoft.
