### ISSUE TITLE
Ellaism Community Weekly Meeting 20 Agenda meeting

### ISSUE THREAD

**Issue by stevemulligan** [ellaism/meta#47]
- Discuss results of hard fork
- Ellaism Wallet in Fdroid, and why getting a wallet from Fdroid might be preferred by some
- Congrats to @BAlgimantas (Iam3) for getting Ellaism into Andreas M. Antonopoulos new book on Ethereum
- Status of secondary explorer from Limax
- ethminer progress on Ledger support
- CS_Akira talk about etc-explorer fork

**Comment by majordutch** [comment]
Meeting notes here:
https://github.com/ellaism/meta/blob/master/logs/20180804-dev-meeting.md
