### ISSUE TITLE
Ellaism Community Weekly Meeting 21

### ISSUE THREAD

**Issue by ellaismer** [ellaism/meta#51]
* **Meeting time**: Saturday 11/03/2018, at 16:00 UTC
* **Meeting location**: [Discord server](https://discord.ellaism.org)

**Comment by majordutch** [comment]
~~Could not find any meeting notes to reference.~~

Meeting notes here:
https://github.com/ellaism/meta/blob/master/logs/20181103-dev-meeting.md
