### ISSUE TITLE
Issue Tracker and Project Clean Up

### ISSUE THREAD

**Issue by majordutch** [ellaism/meta#55]
Hey everyone, I think it's time that we clean up any stale issues and re-evaluate tasks within the Project Management project. This will help us better understand where we need to concentrate our efforts in order to begin expanding the Ellaism ecosystem.

I would be happy to donate a portion of my free time and manage this for you.

Paging @ellaismer @stevemulligan

**Comment by stevemulligan** [comment]
This is great! Let me know if I can help with anything.

**Comment by ellaismer** [comment]
@majordutch Thank you for this! I invited you to the Ellaism org and gave you project manager role. You should now be able to manage issues/PRs. :)

**Comment by majordutch** [comment]
Thank you both! I will get started on this.

**Comment by majordutch** [comment]
Re-opening this issue in order to generate discussion on the following:

I would like to see if it is possible to get status updates, or at a minimum, gauge the community's sentiment on whether or not a project is necessary at this time.

1. ENS Feature Request #23 
2. Pool Software WishList #19 
3. Explorer Wishlist #12 
4. Project: Dapps Migration #6 
5. Project: BTC Relay #6 

I know for a lot of these we may need @ellaismer to chime in, but I'd also like to hear feedback from others. I will also post this as an issue on the meta repo in case others feel more comfortable responding there.

The immediate goal here is to see where we stand on the existing projects and determine which items need further work and others that can shelved for an indeterminate period of time.

This has also been cross-posted in the #umbrella channel on the [Ellaism Discord](https://discordapp.com/invite/gz9tURY).

**Comment by stevemulligan** [comment]
I have no ongoing work for any of the above.  I dislike our ENS front end and would like to see that totally replaced.
