### ISSUE TITLE
Consider Disabling GitHub Wiki

### ISSUE THREAD

**Issue by majordutch** [ellaism/meta#57]
I think we should consider disabling the GitHub Wiki in this repo as it appears to be underutilized and likely redundant. We can update messaging in the README to point people to the [Ellaism-hosted wiki](https://wiki.ellaism.org/), if needed.

@ellaismer do you have an opinion on this?

**Comment by ellaismer** [comment]
@majordutch Sounds like a good idea to me. See if other devs may have comments.

cc @stevemulligan @ellaism/project-managers

**Comment by majordutch** [comment]
I see it has been disabled, thanks.
