### ISSUE TITLE
Update Ellaism Information on CoinGecko

### ISSUE THREAD

**Issue by majordutch** [ellaism/meta#59]
Could someone contact CoinGecko and ask them to fix the following:

1. Available/Total Supply
2. Twitter, it currently points to https://twitter.com/EllaismCoin

Additionally, the [Developer](https://www.coingecko.com/en/coins/ellaism/developer#panel) tab currently points to the ellaism/go-ellaism repo. **I am not sure if this is the best repo to showcase, maybe it should be discussed.**

See here:
https://www.coingecko.com/en/coins/ellaism

If I missed anything please let me know.

**Comment by stevemulligan** [comment]
I just submitted an update to coingecko.  I created these endpoints for circulating supply. It's not 100% accurate but it's close enough and gets updated every 5 minutes.

https://bellance.outdoordevs.com/api/circulating_supply
https://bellance.outdoordevs.com/api/circulating_supply?decimal=true

We might need to contact  hello@coingecko.com  if the form doesn't work.  I've submitted this form before and the record wasn't updated.

**Comment by majordutch** [comment]
Thanks @stevemulligan!

**Comment by stevemulligan** [comment]
I kept a list on the wiki of sites that needed info updated here, but it hasn't been updated in a while:

https://wiki.ellaism.org/marketing

**Comment by majordutch** [comment]
Excellent, thanks. I need to browse the wiki to get more familiar with what is there.

**Comment by majordutch** [comment]
It looks like CoinGecko updated the information. Thanks again!
