### ISSUE TITLE
Project: BTC Relay

### ISSUE THREAD

**Issue by ellaismer** [ellaism/meta#6]
This issue is used to keep track of the progress of BTC Relay. Please feel free to comment your ideas or if you would like to help. We'll also soon have an update with a concrete plan for BTC Relay development.

What is planned next:

- [ ] Create a better fetchd script for BTC relay for easy use for relayers. The current fetchd script works, but is reported to be buggy and is not user-friendly for installation.
- [ ] Restore BTC relay atomic swap.
- [ ] Restore EtherEx DEX for Ellaism blockchain.
- [ ] Conduct HTLC swap experiment using smart contracts.
- [ ] Handle the HTLC contract validation problem.
- [ ] Create a safe user interface for the HTLC contract.

One thing to note is that atomic swaps help more in decentralization, but might not be of too much help in terms of speed. The speed of one swap depends on the slower chain for finalization, but indeed once the swap is finished, some small transactions can be better handled on the faster chain.

We limit the scope of this project to BTC relay and HTLC. There're other methods to handle cross-chain operations, like creating side chains. They will be discussed in separate projects.

Relevant projects:

* The original BTC Relay repository created by ConsenSys: https://github.com/ethereum/btcrelay
* A decentralized (but discontinued) exchange built on BTC Relay: https://github.com/etherex/etherex
* Zcash Relay: https://github.com/ConsenSys/Project-Alchemy
* HTLC demo: https://medium.com/@DontPanicBurns/ethereum-cross-chain-atomic-swaps-5a91adca4f43

**Comment by tbates76** [comment]
there anything in place to protect contracts?

**Comment by ellaismer** [comment]
@tbates76 Didn't quite get what you mean. Can you elaborate?

Contracts are always secured by the network. That is, they're as secured as it is designed and implemented. We definitely need security audit, testing and code review to make sure we would not be troubled by contract bugs.

**Comment by tbates76** [comment]
Two things. 
 1) How will the tx for the btc relay be secured so that User A doesn't look up the info for user B and withdraw. 
 2) The issue Eth had with contracts recently, where contracts were locked up, is Ellaism exposed to that?

**Comment by ellaismer** [comment]
1. BTC chain is public. So everyone can lookup the info for user B. Atomic swap usually works with a pre-given address. You need to send on the Ellaism chain a proof that you have send a BTC transaction to a pre-given address. So in this case, no matter who submit the transaction to BTC relay, the rightful owner is already known.
2. Ellaism is not affected by the recent Parity multi-sig hack. As said above, we do need security audit, testing and code review to make sure future contracts don't suffer from similar problems.
