### ISSUE TITLE
Administrative Access to Ellaism GitHub

### ISSUE THREAD

**Issue by majordutch** [ellaism/meta#64]
Hi @ellaismer, the small community that you left behind would like to continue on with this project. Can you please give me administrative access to the Ellaism GitHub?

Thank you.

**Comment by ellaismer** [comment]
I'm back!

**Comment by majordutch** [comment]
I am sure some will be happy to hear this, however my request still stands. The management of the Ellaism repositories should not hinge on a single individual. As it is, I had to create a separate organization to continue working on some projects. It would be ideal to bring these back in to the original organization.

**Comment by ellaismer** [comment]
@majordutch ~~I can't give you owner role now, but I'd be happy to do it once I can trust you more. For any other type of administrative access, just let me know and I'm sure it can be easily fulfilled.~~

I have transferred the admin access of this Github org to you!
