### ISSUE TITLE
Project: Dapps Migration

### ISSUE THREAD

**Issue by ellaismer** [ellaism/meta#7]
Migrate existing useful Ethereum dapps to Ellaism chain.

* [X] ENS
* [X] CarbonVote
* [ ] Tokenmint
* [x] [ProveIt](https://github.com/NoahZinsmeister/ProveIt)

**Comment by stevemulligan** [comment]
Migrated Prove It.

https://proveit.outdoordevs.com/

https://github.com/stevemulligan/ProveIt
